# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet C:/Users/user/lab11/lab11.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/user/lab11/lab11.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/define.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/parameter.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/timescale.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/kcuart_tx.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/kcuart_rx.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/bbfifo_16x8.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/UCLOCK.V
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/uart_tx.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/uart_rx.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/uart_control.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/kcpsm3.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/UART.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/MuxS2M.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/MuxM2S.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/Master03.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/Master02.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/Master01.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/DefaultSlave.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/Decoder.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/ISE2/Arbiter.v
  C:/Users/user/lab11/lab11.srcs/sources_1/imports/Desktop/EASY.v
}
read_xdc C:/Users/user/lab11/lab11.srcs/constrs_1/imports/xdc_code/EASY.xdc
set_property used_in_implementation false [get_files C:/Users/user/lab11/lab11.srcs/constrs_1/imports/xdc_code/EASY.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/user/lab11/lab11.cache/wt [current_project]
set_property parent.project_dir C:/Users/user/lab11 [current_project]
catch { write_hwdef -file EASY.hwdef }
synth_design -top EASY -part xc7a100tcsg324-1
write_checkpoint EASY.dcp
report_utilization -file EASY_utilization_synth.rpt -pb EASY_utilization_synth.pb
