# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.cache/wt} [current_project]
set_property parent.project_path {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/CASLAB/project_IP/project_IP.srcs/sources_1/imports/verilog_code/RTL
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs}
  c:/users/caslab/project_ip/project_ip.srcs/sources_1/imports/verilog_code
} [current_project]
add_files {{D:/gitdev/colab/resource/計組 實驗資料/Solution/Lab8/ISE/lab.coe}}
add_files {{d:/gitdev/colab/resource/計組 實驗資料/Solution/Lab10/ISE3/lab.coe}}
add_files -quiet {{D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp}}
set_property used_in_implementation false [get_files {{D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp}}]
read_verilog -library xil_defaultlib {
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/SlaveWrapper.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/control_unit.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/MySRAM_AHB32_Top.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/MuxS2M.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/MuxM2S.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/GPIO.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/DefaultSlave.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/Decoder.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/Arbiter.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/EASY.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/RISC32_File.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/timescale.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/verilog_code/define.v}
  {D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/lab8 _takeaway0/risc32.v}
}
read_edif {{D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/sources_1/imports/lab8 _takeaway0/risc32.edif}}
read_xdc {{D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/constrs_1/imports/xdc_code/EASY.xdc}}
set_property used_in_implementation false [get_files {{D:/gitdev/colab/test/lab8/lab8 _takeaway0/lab8.srcs/constrs_1/imports/xdc_code/EASY.xdc}}]

catch { write_hwdef -file EASY.hwdef }
synth_design -top EASY -part xc7a100tcsg324-1
write_checkpoint -noxdef EASY.dcp
catch { report_utilization -file EASY_utilization_synth.rpt -pb EASY_utilization_synth.pb }
